### ISSUE TITLE
Out of bounds write in tutor7pp fluence scoring arrays from floating point rounding issue

### ISSUE THREAD

**Issue by mxxo** [nrc-cnrc/EGSnrc#863]
I think I've found an potential issue with the `tutor7pp` fluence scorring array bin math with Address Sanitizer. I am using a modified version of `tutor7pp` called `mevegs` that shares the same fluence scoring code.

The asan report is: 
```text
==21539==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x623000003618 at pc 0x000000531196 bp 0x7ffe1fab1f30 sp 0x7ffe1fab1f28
READ of size 2 at 0x623000003618 thread T0
    #0 0x531195 in EGS_ScoringSingle::score(unsigned short, double) /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_scoring.h:79
    #1 0x531195 in EGS_ScoringArray::score(int, double) /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_scoring.h:245
    #2 0x531195 in Mevegs_Application::ausgab(int) /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/user_codes/mevegs/mevegs.cpp:395
    #3 0x5432be in egs_ausgab_ /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_advanced_application.cpp:1285
    #4 0x5d8817 in photon_ /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/user_codes/mevegs/egsnrc_linux.F:19399
    #5 0x65de15 in egs_shower_ /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/interface/egs_interface2.c:96
    #6 0x53fe2a in EGS_AdvancedApplication::shower() /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_advanced_application.cpp:873
    #7 0x2ad674b0f7d3 in EGS_Application::simulateSingleShower() /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_application.cpp:945
    #8 0x2ad674b0eab9 in EGS_Application::runSimulation() /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_application.cpp:894
    #9 0x40d407 in main /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/user_codes/mevegs/mevegs.cpp:782
    #10 0x2ad6753f3e1a in __libc_start_main (/cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libc.so.6+0x23e1a)
    #11 0x40d8a9 in _start (/project/6003708/morok/EGSnrc/egs_home/bin/linux/mevegs+0x40d8a9)

0x623000003618 is located 24 bytes to the right of 6400-byte region [0x623000001d00,0x623000003600)
allocated by thread T0 here:
    #0 0x4f408f in operator new[](unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cc:107
    #1 0x2ad674b27053 in EGS_ScoringArray::EGS_ScoringArray(int) /home/morok/projects/def-jmcdonal/morok/EGSnrc/HEN_HOUSE/egs++/egs_scoring.cpp:47
```

The fluence arrays are set up here with 200 bins:
https://github.com/nrc-cnrc/EGSnrc/blob/a6fc389c6465c949645380976f38a013a639759c/HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp#L319-L320

The actual out-of-bounds read from the report occurs in `EGS_ScoringSingle::score`, line 79, but since it's just reading a member variable, I suspected this `EGS_ScoringSingle` was past the end of the `EGS_ScoringArray` (i.e. `bin >= 200`):
https://github.com/nrc-cnrc/EGSnrc/blob/a6fc389c6465c949645380976f38a013a639759c/HEN_HOUSE/egs%2B%2B/egs_scoring.h#L78-L85

The bin number is calculated here:
https://github.com/nrc-cnrc/EGSnrc/blob/a6fc389c6465c949645380976f38a013a639759c/HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp#L464-L472

I think what's happening is with the default round-to-nearest floating-point rounding, there are cases where `r2 < 400`, but `sqrt(r2)` rounds to `20.0`, as the true answer is closer to `20.0` (`0x1.4000000000000p+4`) than the previous representable double `19.999999999999996` ( `0x1.3ffffffffffffp+4`) leading to an eventual out of bounds write. This is very rare, requiring specific `r2` (and therefore `x[np]` and `y[np]`) values. I observed it in two of ten parallel jobs in a 1 billion history simulation, one of which was ~65 million histories into a simulation. The specific case I saw was for `r2 = 399.99999999999994`: 

```cpp
double r2 = 399.99999999999994;
double result = std::sqrt(r2); // = 20.0 with round-to-nearest
int bin = (int)(sqrt(r2)*10.); // 200, out of bounds 
```

Here is a Compiler Explorer link showing this in action, with different results per-compiler and optimization levels: https://godbolt.org/z/dj93jsEq8

### Reproducer
The exact simulation setup is somewhat complicated (I can provide exact steps if necessary), but I have reproduced this crash multiple times to be certain. Without asan on, this manifested as a segfault when deleting `gflu` in the user code destructor. Adding a bounds check and rerunning the simulation confirms this is the issue:
```diff
diff --git a/HEN_HOUSE/egs++/egs_scoring.h b/HEN_HOUSE/egs++/egs_scoring.h
index 76ef058..237f05c 100644
--- a/HEN_HOUSE/egs++/egs_scoring.h
+++ b/HEN_HOUSE/egs++/egs_scoring.h
@@ -242,7 +242,11 @@ public:
       region \a ireg
      */
     inline void score(int ireg, EGS_Float f) {
-        result[ireg].score(current_ncase_short,f);
+        if (ireg < this->nreg) {
+            result[ireg].score(current_ncase_short,f);
+        } else {
+            egsFatal("ERROR: ireg %d out of bounds for scoring array with %d bins\n", ireg, nreg);
+        }
     };
```
```
ERROR: ireg 200 out of bounds for scoring array with 200 bins
```
Changing the bounds check to check `bin` instead of `r2` avoids this issue (the simulation completed without an asan crash). 
```diff
diff --git a/HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp b/HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
index b77d2a7..fa122ab 100644
--- a/HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
+++ b/HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
@@ -462,8 +462,8 @@ int Tutor7_Application::ausgab(int iarg) {
         if (ir == nreg+1) {
             EGS_ScoringArray *flu = the_stack->iq[np] ? eflu : gflu;
             EGS_Float r2 = the_stack->x[np]*the_stack->x[np] + the_stack->y[np]*the_stack->y[np];
-            if (r2 < 400) {
-                int bin = (int)(sqrt(r2)*10.);
+            int bin = (int)(sqrt(r2)*10.);
+            if (bin < 200) {

                 aux = the_stack->wt[np]/the_stack->w[np];
                 if (aux > 0) {
```

**Comment by rtownson** [comment]
What a thorough bug report! Good work.
